### ISSUE TITLE
Lab B2 - Index your data in Azure AI Search - Wrong search key setting in code

### ISSUE THREAD

**Issue by nmenigonms** [microsoft/copilot-camp#393]
Custom copilot does not return any candidate in the "Lab B2 - Index your data in Azure AI Search". 

This is due to an error in the search ai env settings. Code in Step 1 mentions an env var name called "azureSearchKey", and code in Step2 is using another env name called "$searchApiKey".

Just match the env var name and it works.

**Comment by aycabas** [comment]
Hi @nmenigonms, thanks for your feedback. $searchApiKey inside the prompts/chat/config.json is a placeholder, so it doesn't map to any key. We are using data dataSource.parameters.authentication.key key map our key from env to our datasource. You can see more from the code sample here: https://github.com/microsoft/copilot-camp/blob/855eecaef0f64ced2d0dc86ce3803fccb95c4d0f/src/custom-engine-agent/Lab02-RAG/CareerGenie/src/app/app.ts#L34 

So in that case, using "azureSearchKey" in env and config.ts doesn't block us from passing the key because that is not directly tied into the name of $searchApiKey but to "key" parameter. I hope that helps.
